apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: weather-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/weather-api
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: WEATHER_API_KEY
          value: "YOUR_WEATHER_API_KEY"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi

